services:
  app:
    build: .
    ports:
      - "8090:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=zesty_sips
    networks:
      - zesty-network

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=zesty_sips
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zesty-network

volumes:
  postgres_data:

networks:
  zesty-network:
    driver: bridge